remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: BotOfTheSpecter Changelog
description: A concise record of updates and changes for the BotOfTheSpecter Twitch Bot, keeping users informed about new features, improvements, and fixes.